### ISSUE TITLE
sample request: create/update transfer config with user credentials and authorization code

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery-datatransfer#101]
We've received several requests in the past weeks for help with user credentials instead of service account credentials.

**Comment by ThatCheck** [comment]
Any update on this ?

**Comment by tswast** [comment]
It's still on our backlog of potential samples to write.

One reason we haven't worked on this is due to problems testing (in CI/CD) a sample that requires a user account instead of service account. I recently learned that the Google Auth library has some system tests with user credentials ([code](https://github.com/googleapis/google-auth-library-python/blob/3c3fbf40b07e090f2be7fac5b304dbf438b5cd6c/system_tests/noxfile.py#L36)), so maybe we can use similar infrastructure for this code sample.

**Comment by tswast** [comment]
Also, note that we did have some thorough comments in an older version of the code sample on how to do this. See:

https://github.com/googleapis/python-bigquery-datatransfer/blob/eacdcb9a8c1e1b3888fbed014fda013fec73175e/samples/create_scheduled_query.py
