### ISSUE TITLE
curl for getting authorization code 

### ISSUE THREAD

**Issue by keunsoopcoop** [googleapis/python-bigquery-datatransfer#108]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

I am developing a Python script to create multiple Data Transfer jobs. It looks like `authorization_code` for `create_transfer_config` function becomes invalid once it is used, so I need to get the new `authorization_code` for each request (Please correct me if I am wrong).

I can get `authorization_code` through web browser with logging in with my google account, but I am not sure how to do this in programatic way. Can anyone provide me curl for the call for `authoriztion_code`? I am using the following form of url for getting `authorization_code`.
`https://www.gstatic.com/bigquerydatatransfer/oauthz/auth?client_id=<client_id>&scope=<data_source_scopes>&redirect_uri=<redirect_uri>`

**Comment by tswast** [comment]
Because of how the OAuth 2.0 protocol works, the user does need to open a browser to get the authorization code at least once. Note: the second time a user accesses the BQ-DTS API, the authorization code can be omitted.

**Comment by keunsoopcoop** [comment]
@tswast Thanks for the tip! Now I do not need to refresh authorization_code as it is needed only at the first call!
