### ISSUE TITLE
BigQuery Data Transfer Notifications API Enablement

### ISSUE THREAD

**Issue by ccao93** [googleapis/python-bigquery-datatransfer#13]
I have been notified that the rollout for BigQuery Data Transfer Notifications API is completed. However, I'm still not able to set it up via `google.protobuf.json_format.ParseDict` & `bigquery_datatransfer_v1.types.TransferConfig()`. The error I got was:

```
Message type "google.cloud.bigquery.datatransfer.v1.TransferConfig" has no field named "notification_pubsub_topic".
 Available Fields(except extensions): ['name', 'destinationDatasetId', 'displayName', 'dataSourceId', 'params', 'schedule', 'scheduleOptions', 'dataRefreshWindowDays', 'disabled', 'updateTime', 'nextRunTime', 'state', 'userId', 'datasetRegion']
```

May I ask if there is any plan to add this field to `bigquery_datatransfer_v1.types.TransferConfig()`?

Thanks

**Comment by guillaumeblaquiere** [comment]
Similar to #17

**Comment by ccao93** [comment]
It's already added to gapi here: https://googleapis.dev/python/bigquerydatatransfer/latest/gapic/v1/types.html#google.cloud.bigquery_datatransfer_v1.types.TransferConfig

**Comment by shollyman** [comment]
Looking at the deltas from 0.4.1, I believe the notification fields are present in the 1.0.0 release (released yesterday).  If that's incorrect, reopen this issue.

**Comment by ccao93** [comment]
I don't think the notification field has been added in the 1.0.0 release. Still have the error of ```'TransferConfig' object has no attribute 'notification_pubsub_topic'``` and seems the field added was `service_account_name` instead of notification field.

**Comment by ccao93** [comment]
@shollyman Can you help to reopen this issue, seems I don't have the access to reopen it myself. Thanks

**Comment by guillaumeblaquiere** [comment]
Agree with @ccao93. The notification_pubsub_topic is defined in [this file](https://github.com/googleapis/python-bigquery-datatransfer/blob/master/google/cloud/bigquery_datatransfer_v1/proto/transfer_pb2.py), which imported [here](https://github.com/googleapis/python-bigquery-datatransfer/blob/release-v1.0.0/google/cloud/bigquery_datatransfer_v1/gapic/data_transfer_service_client.py#L45) but never used in the rest of code.

Something is missing, or I miss something. Anyway, if it works, an example is welcome!!

**Comment by shollyman** [comment]
Reopened the issue to keep an eye on this.  Wanted to verify we're talking about the same time, so here's my understanding:

TransferConfig entities expose two notification mechanisms:  a reference to a pubsub topic 

The datatransfer backend exposes two fields:  `notification_pubsub_topic` which can hold a reference to a pubsub topic, or `email_preferences` which governs (via a boolean) whether to send an email to the owner of the transfer config when a specific transfer run fails.

Checking public docs here: https://cloud.google.com/bigquery-transfer/docs/transfer-run-notifications I don't see any references to other notification facility.  In both cases, the datatransfer is delivering a notification to another service, so you'd leverage them to process the notification (e.g. consuming messages from a pubsub topic).

We don't currently have a great set of examples for setting up a transfers, so using the scheduled query example at https://cloud.google.com/bigquery/docs/scheduling-queries#setting_up_a_scheduled_query you'd amend the transfer_config dict to something like:
```
transfer_config = google.protobuf.json_format.ParseDict(
    {
        "destination_dataset_id": dataset_id,
        "display_name": "Your Scheduled Query Name",
        "data_source_id": "scheduled_query",
        "params": {
            "query": query_string,
            "destination_table_name_template": "your_table_{run_date}",
            "write_disposition": "WRITE_TRUNCATE",
            "partitioning_field": "",
        },
        "schedule": "every 24 hours",
        "notification_pubsub_topic": "projects/my-project-id/topics/my-topic-id",
    },
    bigquery_datatransfer_v1.types.TransferConfig(),
)

```

I do see that the annotations for the API are terse and don't explain the format of the notification_pubsub_topic, I'll submit an issue for the backend team to correct that in their documentation but you can see the pattern in my example snippet.

Does this align with what you're asking?  Or is there some other notification mechanism you're referring to?

**Comment by shollyman** [comment]
filed 150976467 internally about improving the docstrings for the pubsub id format

**Comment by guillaumeblaquiere** [comment]
@shollyman, your example works. Thanks you.

However:

 *  I expected an object to fill with the expected field. Here, parsing a dict into a gRPC proto definition is very low level for every developers, and not consistent with the other libraries.
* My IDE doesn't know TransferConfig()
![image](https://user-images.githubusercontent.com/1756715/76143752-4e0d6a00-607a-11ea-9f2a-8d15c9f08434.png)

**Comment by ccao93** [comment]
@shollyman Thanks for the help. Seems I had some version issue. After rebooting my laptop, the issue has been fixed.
