### ISSUE TITLE
Support email notifications & pubsub for transfer configs when creating via python SDK

### ISSUE THREAD

**Issue by adamcunnington-2sixty** [googleapis/python-bigquery-datatransfer#17]
Please support the emailNotifications & pubsub options. Currently, when creating a Data Transfer run via python SDK, we can't programmatically manage notifications. I believe both the REST and gRPC apis expose this as an option.

**Comment by guillaumeblaquiere** [comment]
I have the same requirement. 
Similar to #13

**Comment by shollyman** [comment]
Looking at the deltas from 0.4.1, I believe the notification fields are present in the 1.0.0 release (released yesterday). If that's incorrect, reopen this issue.
