### ISSUE TITLE
Documentation for `name` param in get/delete transfer config very unclear

### ISSUE THREAD

**Issue by adamcunnington-2sixty** [googleapis/python-bigquery-datatransfer#18]
The documentation describes that the first parameter to the get_transfer_config & delete_transfer_config methods should be "name". As far as I can tell, the name is the projects/foo/locations/foo/transferConfigs/unique-guid which is well, unique - how can this be obtained?! The only way you would have access to that unique ID is if you have access to the transfer config object in which case, you wouldn't need to get it!

The example shows that name can be generated from the classmethod, client.project_transfer_config_path.

But that classmethod wants "transfer_config" as a parameter which is circular and the documentation is [incredibly light](https://googleapis.dev/python/bigquerydatatransfer/latest/gapic/v1/api.html#google.cloud.bigquery_datatransfer_v1.DataTransferServiceClient.project_transfer_config_path).

When I try passing the object that I ultimately send to create_transfer_config, it doesn't work.

I can provide more detail if necessary but I'm hoping that someone is already aware of this and can either call out what i'm doing wrong and/or fix the documentation.

**Comment by shollyman** [comment]
Thanks for providing the feedback.  The nature of this API (and it's documentation) are generated from the service definitions we get from the backend, so I've filed https://issuetracker.google.com/issues/150962884 in the public issue tracker to flag this for followup from the backend team responsible for the datatransfer API.

The other comment I'd add here are that you typically get the unique identifier as part of the creation response, or via iteration of created transfer configs via the corresponding List operation.

At this time, I'm going to go ahead and close this github issue in favor of the issuetracker link above. I'd encourage you to respond on that issue for followups.
