### ISSUE TITLE
Invalid argument Error when trying to update credentials of DTS job

### ISSUE THREAD

**Issue by arubafna** [googleapis/python-bigquery-datatransfer#192]
I am trying to update the credential of a dts job that was created using a user account. Instead of the user account I want to use a service account to configure the dts.
The [documentation ](https://cloud.google.com/bigquery-transfer/docs/working-with-transfers#python_3) suggests the following python code which errors out.
Even the cli command: bq update --transfer_config --update_credentials --service_account_name=<SA name> <resource_name> errors out with
InvalidArgument: 400 Request contains an invalid argument

**Comment by tswast** [comment]
The code sample at https://github.com/googleapis/python-bigquery-datatransfer/blob/5e02bd166149b4ef7ee0f295fdcb6a3570ec2f58/samples/snippets/manage_transfer_configs.py#L72-L105 has been tested to work, but I see other customers are also struggling with this in internal issue 206858465.

I suggest we update our code samples to use the explicit request object such as the [UpdateTransferConfigRequest](https://cloud.google.com/python/docs/reference/bigquerydatatransfer/latest/google.cloud.bigquery_datatransfer_v1.types.UpdateTransferConfigRequest) class. This would make typos easier to spot than with a dictionary as the current samples are using.

**Comment by meredithslota** [comment]
Closing this — the tests are still passing and we've also added generated samples that use the explicit request object: https://github.com/googleapis/python-bigquery-datatransfer/blob/main/samples/generated_samples/bigquerydatatransfer_v1_generated_data_transfer_service_update_transfer_config_sync.py and others in that folder.
