### ISSUE TITLE
list_transfer_configs does not list all the transfer configurations of a project

### ISSUE THREAD

**Issue by christophedcpm** [googleapis/python-bigquery-datatransfer#198]
#### Environment details

  - OS type and version:
  - Python version: Python 2.7.17
  - pip version: pip 20.2.4
  - `google-cloud-bigquery-datatransfer` version:  1.1.1

#### Steps to reproduce

  1. Create multiple transfer configuration in a project
  2. Try to list all the configuration -> only one of the configuration is return

#### Code example

```python
 from google.cloud import bigquery_datatransfer

transfer_client = bigquery_datatransfer.DataTransferServiceClient()
parent = transfer_client.project_path('pj-sbx-key-dummy-fl1') # all the configuration are part of this project
for config in transfer_client.list_transfer_configs(parent=parent):
    print(config.destination_dataset_id)
```

**Comment by tswast** [comment]
@christophedcpm Are all the configs in the same location? I suspect that perhaps the backend API assumes a default location when none is set.

**Comment by meredithslota** [comment]
Quick question - are all the transfers going into the same `destination_dataset_id` location? I wonder if it might be de-duping the destination dataset. I'm not sure. I assigned this to @tswast to investigate.

**Comment by meredithslota** [comment]
(Jinx, sorry Tim!)

**Comment by christophedcpm** [comment]
@tswast no indeed, the destination dataset are in different locations. The workaround I have to specify the location manually  for the parent argument `/project/$projectid/location/$location`. But this is a problem for me cause I just want to list all transfer config present in the project and I do not know in advance which location they are located in. 
I could loop over all locations, but this very inefficient and does not sound like a proper solution.

**Comment by tswast** [comment]
Unfortunately this is a limitation of the backend. I recommend filing a support case or an issue in the backend team's public tracker here: https://issuetracker.google.com/issues/new?component=187149&template=1162659

**Comment by christophedcpm** [comment]
@tswast understood, thanks for the confirmation.
