### ISSUE TITLE
BigQuery Data Transfer: Missing documentation of "params" parameter in TransferConfig

### ISSUE THREAD

**Issue by antonimaciej** [googleapis/python-bigquery-datatransfer#2]
The "params" parameter in [TransferConfig](https://googleapis.github.io/google-cloud-python/latest/bigquery_datatransfer/gapic/v1/types.html#google.cloud.bigquery_datatransfer_v1.types.TransferConfig) is not document. The only information I could find is "Data transfer specific parameters." which is not sufficient.

**Comment by guypld** [comment]
Unfortunately this one is still relevant, 
also for the REST API:
https://cloud.google.com/bigquery-transfer/docs/reference/datatransfer/rest/v1/projects.locations.transferConfigs#TransferConfig

I can't find out how to use '**cross_region_copy**' and copy a BQ Dataset to a different project.

**Comment by meredithslota** [comment]
The original issue has been resolved; the API documentation now includes documentation on the `params` object: https://cloud.google.com/bigquery-transfer/docs/reference/datatransfer/rest/v1/projects.locations.transferConfigs.runs?hl=en It's an output-only field and is specific to the data source. 

Copying datasets is a beta feature but there is new documentation there as well: 
https://cloud.google.com/bigquery/docs/copying-datasets#api - for doing so via the API
https://cloud.google.com/bigquery/docs/copying-datasets#python - for doing so with the Python client library

I'm going to close this one out for now but please create a new issue if you are stuck on the dataset copy feature. Thanks!
