### ISSUE TITLE
feature: ability to label a scheduled query

### ISSUE THREAD

**Issue by terekete** [googleapis/python-bigquery-datatransfer#201]
Is your feature request related to a problem? Please describe.
Unsure if this exists already, if not this would be a feature request.
Looking for an ability to label schedule query jobs. Is there a means to add labels so the scheduled jobs can container metadata when they appear in the INFORMATION_SCHEMA.

Describe the solution you'd like
One would see a label similar to those seen in Big Query.

Describe alternatives you've considered
N/A

Additional context
Does this exist already ?

**Comment by meredithslota** [comment]
You can name your scheduled queries — this page has a code sample showing how: https://cloud.google.com/bigquery/docs/scheduling-queries#setting_up_a_scheduled_query The parameter for the transfer config is `display_name`, I think.
