### ISSUE TITLE
keep getting '404 Requested entity was not found.' when trying sample code

### ISSUE THREAD

**Issue by CharmanderJieniJieni** [googleapis/python-bigquery-datatransfer#252]
I am trying to run the sample python code to copy datasets between projects as per described here: https://cloud.google.com/bigquery/docs/copying-datasets#setting_up_a_dataset_copy to copy dataset, and local execution keeps throwing `404 Requested entity was not found.` 

I have confirmed that I have inject correct dataset id and project id, only thing I suspect which may cause the problem is that if I look at a transfer job configured through console, it is actually using `project_number` instead of `project_id` as `parent`. However I cannot confirm if that is case due to lack of documentation 

#### Code example

```python
from google.cloud import bigquery_datatransfer


def main():
    transfer_client = bigquery_datatransfer.DataTransferServiceClient()
    destination_project_id = "project-dest" #replace me
    source_project_id = "project-source" #replace me
    source_dataset_id = "dataset_source" #replace me
    destination_dataset_id = f"dataset_dest" #replace me
    transfer_config = bigquery_datatransfer.TransferConfig(
        destination_dataset_id=destination_dataset_id,
        display_name="test transfer",
        data_source_id=source_dataset_id,
        params={
            "source_project_id": source_project_id,
            "source_dataset_id": source_dataset_id,
        },
        schedule="every 24 hours",
    )

    transfer_config = transfer_client.create_transfer_config(
        parent=f"projects/{destination_project_id}",
        transfer_config=transfer_config,
    )

if __name__ == "__main__":
    main()
```

**Comment by tswast** [comment]
There's not enough information in this question for me to help you. Could you try upgrading to the latest `google-api-core` library and print the `error_details` property of the exception?

**Comment by CharmanderJieniJieni** [comment]
@tswast I am using latest version `3.4.1` on and python3.7.9. The detail error inside exception is below

<_InactiveRpcError of RPC that terminated with:
	status = StatusCode.NOT_FOUND
	details = "Requested entity was not found."
	debug_error_string = "{"created":"@1637212953.720768000","description":"Error received from peer ipv4:xxxxxxxxx:443","file":"src/core/lib/surface/call.cc","file_line":1070,"grpc_message":"Requested entity was not found.","grpc_status":5}"
>

**Comment by CharmanderJieniJieni** [comment]
I have narrowed it down that it is underlayer method call transfer_client.check_valid_creds() throwing this exception. Digging further

**Comment by CharmanderJieniJieni** [comment]
Works! Thanks @ashok133 ! I thought `cross_region_copy` was just a dummy dataset name, don't know why it is called cross_region even I am copying across same region. Anyways thanks a lot!
