### ISSUE TITLE
BigQuery Data Transfer: list_locations missing

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery-datatransfer#4]
I would expect to see a `list_locations` method that takes a project ID in the [DataTransferServiceClient class](https://googlecloudplatform.github.io/google-cloud-python/latest/bigquery_datatransfer/gapic/v1/api.html#google.cloud.bigquery_datatransfer_v1.DataTransferServiceClient).

Docs for this API method:

https://cloud.google.com/bigquery/docs/reference/datatransfer/rest/v1/projects.locations

Actual API endpoint:

https://bigquerydatatransfer.googleapis.com/v1/projects/swast-scratch/locations?access_token=YOUR_ACCESS_TOKEN

( Replace `YOUR_ACCESS_TOKEN` with an access token with `gcloud auth print-access-token` )

**Comment by meredithslota** [comment]
@tswast Is this still an issue in the new generators for the reasons described above?

**Comment by tswast** [comment]
@meredithslota Yes. This is still an issue.

A potential alternative solution is to create clients for the "location" service (https://github.com/googleapis/googleapis/tree/master/google/cloud/location) and override the endpoints to point at the BigQuery DTS endpoint.

**Comment by meredithslota** [comment]
Blocked by internal issue 235516423 to include the `location` service in this library.

**Comment by parthea** [comment]
I've changed this to a feature request as the internal issue is treated as a feature request.

**Comment by chalmerlowe** [comment]
based on priorities and work load, closing this as will not fix.

**Comment by parthea** [comment]
Googlers see cl/499263653

**Comment by parthea** [comment]
```
pip install google-cloud-bigquery-datatransfer==3.9.0
```

Sample code 
```
from google.cloud import bigquery_datatransfer_v1
from google.cloud.location import locations_pb2

project = '<YOUR_PROJECT_ID>'
name=f'projects/{project}'
request = locations_pb2.ListLocationsRequest(name=name)
client = bigquery_datatransfer_v1.DataTransferServiceClient()

response = client.list_locations(request=request)
print(response)
```
