### ISSUE TITLE
Samples tests are failing

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery-datatransfer#51]
https://source.cloud.google.com/results/invocations/ba4c0c8d-404c-4199-86dd-cc4f68c54b2b/targets/github%2Fpython-bigquery-datatransfer%2Fsamples/tests;group=samples.tests.test_update_transfer_config;test=test_update_config_sample;row=3

Need to request more quota?

```
E   google.api_core.exceptions.ResourceExhausted: 429 Quota exceeded for quota group 'DataTransferServiceOthersGroup' and limit 'ProjectQps' of service 'bigquerydatatransfer.googleapis.com' for consumer 'project_number:1012616486416'.
```

**Comment by plamut** [comment]
FWIW, I've seen that a couple of times in other libraries, too, resulting in CI check failures.

**Comment by tswast** [comment]
I've requested more quota. I believe this is fixed.
