### ISSUE TITLE
AttributeError: 'DESCRIPTOR' (google documentation)

### ISSUE THREAD

**Issue by Iuiu1234** [googleapis/python-bigquery-datatransfer#63]
Using google documentation 
[link](https://cloud.google.com/bigquery/docs/scheduling-queries#setting_up_a_scheduled_query)
code: sample_create_transfer_config in
[link](https://github.com/googleapis/python-bigquery-datatransfer/blob/a88deabe07fbb39a3b28c8726b9856018fb1431e/samples/create_scheduled_query.py)

```
transfer_config = google.protobuf.json_format.ParseDict(
    {
        "destination_dataset_id": dataset_id,
        "display_name": "Your Scheduled Query Name",
        "data_source_id": "scheduled_query",
        "params": {
            "query": query_string,
            "destination_table_name_template": "your_table_{run_date}",
            "write_disposition": "WRITE_TRUNCATE",
            "partitioning_field": "",
        },
        "schedule": "every 24 hours",
    },
    bigquery_datatransfer_v1.types.TransferConfig(),
)
```

Raises the error
AttributeError: 'DESCRIPTOR'

To SOLVE the problem I did add `._pb' to TransferConfig:

```
transfer_config = google.protobuf.json_format.ParseDict(
    {
        "destination_dataset_id": dataset_id,
        "display_name": "Your Scheduled Query Name",
        "data_source_id": "scheduled_query",
        "params": {
            "query": query_string,
            "destination_table_name_template": "your_table_{run_date}",
            "write_disposition": "WRITE_TRUNCATE",
            "partitioning_field": "",
        },
        "schedule": "every 24 hours",
    },
    bigquery_datatransfer_v1.types.TransferConfig()._pb,
)
```

**Comment by Wukkkinz-0725** [comment]
It really worked and helped me a lot, thanks luiu. By the way `_pb` is the protected class in TransferConfig(), I think official should make some modification in this part.

**Comment by Wukkkinz-0725** [comment]
> Using google documentation
> [link](https://cloud.google.com/bigquery/docs/scheduling-queries#setting_up_a_scheduled_query)
> code: sample_create_transfer_config in
> [link](https://github.com/googleapis/python-bigquery-datatransfer/blob/a88deabe07fbb39a3b28c8726b9856018fb1431e/samples/create_scheduled_query.py)
> 
> ```
> transfer_config = google.protobuf.json_format.ParseDict(
>     {
>         "destination_dataset_id": dataset_id,
>         "display_name": "Your Scheduled Query Name",
>         "data_source_id": "scheduled_query",
>         "params": {
>             "query": query_string,
>             "destination_table_name_template": "your_table_{run_date}",
>             "write_disposition": "WRITE_TRUNCATE",
>             "partitioning_field": "",
>         },
>         "schedule": "every 24 hours",
>     },
>     bigquery_datatransfer_v1.types.TransferConfig(),
> )
> ```
> 
> Raises the error
> AttributeError: 'DESCRIPTOR'
> 
> To SOLVE the problem I did add `._pb' to TransferConfig:
> 
> ```
> transfer_config = google.protobuf.json_format.ParseDict(
>     {
>         "destination_dataset_id": dataset_id,
>         "display_name": "Your Scheduled Query Name",
>         "data_source_id": "scheduled_query",
>         "params": {
>             "query": query_string,
>             "destination_table_name_template": "your_table_{run_date}",
>             "write_disposition": "WRITE_TRUNCATE",
>             "partitioning_field": "",
>         },
>         "schedule": "every 24 hours",
>     },
>     bigquery_datatransfer_v1.types.TransferConfig()._pb,
> )
> ```
It really worked and helped me a lot, thanks luiu. By the way _pb is the protected class in TransferConfig(), I think official should make some modification in this part.

**Comment by tswast** [comment]
Thank you for the report. I have updated today the documentation to match the working sample at https://github.com/googleapis/python-bigquery-datatransfer/blob/master/samples/create_scheduled_query.py

**Comment by kabirivan** [comment]
I can revolve it, in this way:

Step 1: Import this lib

`from google.protobuf.json_format import MessageToDict`

Step 2: Send a request

`    agent = Agent(
        parent=parent,
        display_name=display_name,
        default_language_code="en",
        time_zone="America/Los_Angeles",
    )
`

`    request = SetAgentRequest(
        agent=agent,
    )`


Step 3: Convert response to JSON [Look here, add ".pd"]

`  response = await agent_client.set_agent(request=request)
    new_response = MessageToDict(response._pb)`

`  return IGetResponseBase(data=new_message)`




<img width="1419" alt="Screen Shot 2022-08-18 at 19 19 01" src="https://user-images.githubusercontent.com/48870806/185516607-759ba70e-e421-46e1-8f30-56a0e96e2c86.png">
