### ISSUE TITLE
AttributeError: 'DataTransferServiceClient' object has no attribute 'location_path'

### ISSUE THREAD

**Issue by Iuiu1234** [googleapis/python-bigquery-datatransfer#66]
If run tutorial command
```
from google.cloud import bigquery_datatransfer_v1

client = bigquery_datatransfer_v1.DataTransferServiceClient()

parent = client.location_path('[PROJECT]', '[LOCATION]')
```

Gives me the error
```
AttributeError: 'DataTransferServiceClient' object has no attribute 'location_path'
```

py3.7
windows
google-api-core==1.22.4
google-auth==1.22.1
google-cloud-bigquery-datatransfer==2.1.0
googleapis-common-protos==1.52.0
grpcio==1.32.0

**Comment by meredithslota** [comment]
Gotcha - I think the tutorial section needs to be updated; just to confirm, are you referencing this page? https://googleapis.dev/python/bigquerydatatransfer/latest/index.html under "Example Usage"?

**Comment by Iuiu1234** [comment]
yes, that's correct.
Where shoul I look instead?

**Comment by varelasavela** [comment]
Same issue for me. Is any workaround to create scheduled query with python sdk for now?

**Comment by Iuiu1234** [comment]
The example in
https://github.com/googleapis/python-bigquery-datatransfer/blob/v2.1.0/samples/create_scheduled_query.py
works.

Idk why the readme is not updated

**Comment by tswast** [comment]
Sent #80 to remove the code sample from the README. Since it's just plain text, it's not tested by our CI infrastructure and is prone to getting out-of-date.
