### ISSUE TITLE
Can you please add sample to create_transfer_config , there is only update example

### ISSUE THREAD

**Issue by shlomiken** [googleapis/python-bigquery-datatransfer#70]
Also looks like the documentation is not updated since it has example with ` client.location_path('[PROJECT]', '[LOCATION]')`
which was removed in 2.0.0 versions.
so a full example is required.

thanks
Shlomi

**Comment by tswast** [comment]
https://github.com/googleapis/python-bigquery-datatransfer/pull/76 adds a `create_transfer_config` example using the 3.0 version of the library (released today)
