### ISSUE TITLE
Please add sample of FieldMask

### ISSUE THREAD

**Issue by gavin-haynes-grow** [googleapis/python-bigquery-datatransfer#9]
All the tests, comments, and samples I found use `{}` as the field mask.

It would be nice to see the actual format documented somewhere:

```
transfer_config = get_transfer_config()
transfer_config.display_name = "Config 42"
field_mask = {"paths": ["display_name"]}
client.update_transfer_config(transfer_config, field_mask)
```

**Comment by shollyman** [comment]
Thanks for the report.  Haven't had much chance to address this one yet.

Two things we need to look into here:

* can we improve discoverability of common types documentation like https://googleapis.dev/python/protobuf/latest/google/protobuf/field_mask_pb2.html ?

* can we improve pages on cloud.google.com to expose these concepts with samples?
